### ISSUE TITLE
Question phylogeny_analysis step hard coded coordinates ?

### ISSUE THREAD

**Issue by agroppi** [asdcid/Chroloplast-genome-assembly#3]
I had a lok in the script "1_gb_gff_fasta.py"
I noticed that some genomic coordinates are "hard coded" in the script : 

```
def grandis_add_missGene(data) :
    
    data.append([9718, 9740, '+', 'tRNA-Gly', 1])
    data.append([10485, 10533, '+', 'tRNA-Gly', 2])

    data.append([5075, 5268, '-', 'rps16', 2])
    data.append([6145, 6184, '-', 'rps16', 1])

    data.append([17880, 22057, '-', 'rpoC2', ''])

    data.append([22223, 23838, '-', 'rpoc1', 2])
    data.append([24572, 25024, '-', 'rpoc1', 1])
    
    data.append([53530, 54382, '-', 'ndhK', ''])

    data.append([81097, 81104, '+', 'petD', 1])
    data.append([81875, 82349, '+', 'petD', 2])

    data.append([61165, 62659, '+', 'accD', ''])

    data.append([129216, 134841, '-', 'ycf1', ''])

    data.append([88932, 89365, '-', 'rpl2', 2])
    data.append([90030, 90420, '-', 'rpl2', 1])

    data.append([125058, 125598, '-', 'ndhA', 2])
    data.append([126659, 127209, '-', 'ndhA', 1])

    data.append([158590, 158980, '+', 'rpl2', 1])
    data.append([159645, 160078, '+', 'rpl2', 2])
```
Are they species specific (Eucalyptus) ? 

Do they have to be adpated in the case of another species ?

Thanks

**Comment by asdcid** [comment]
This step is very case by case. This script is used to split the exon regions and non-exon regions for each  compared species according their annotation. Since Eucalyptus grandis anntation in NCBI missed some genes, I wrote the function (grandis_add_missGene) to correct it. 

In you case, you should split the region by yourself, or you can use other method to do the phylogeny analysis.  

I hope I explained clearly. If not, I can send you an example.

**Comment by agroppi** [comment]
Thanks for your answer.
If you could send me an example adapted to my case and/or other methods to perform phylogeny analysis that's would be great !

**Comment by asdcid** [comment]
Could you send me your email address?

**Comment by agroppi** [comment]
alexis.groppi@u-bordeaux.fr
